[project]
name = "sise-ruche"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4==4.12.3",
    "certifi==2023.11.17",
    "lxml==5.1.0",
    "pymongo==4.6.1",
    "python-dotenv==1.0.0",
]
