[theme]
base = "dark"

# Accent principal (boutons, sliders, progress bars)
primaryColor = "#f4b400"          # jaune miel vif

# Fond principal de l'application
backgroundColor = "#f8ae02"       # jaune chaud / ambre clair

# Sidebar + containers
secondaryBackgroundColor = "#1f1f1f"  # noir charbon

# Texte par défaut
textColor = "#f5f5f5"             # texte clair

# Typographie
font = "sans serif"

# Arrondis (look moderne)
baseRadius = "1.1rem"
buttonRadius = "2.8rem"

# Bordures discrètes
borderColor = "#00000055"


[server]
runOnSave = true
enableStaticServing = true
