[theme]
base = "dark"
primaryColor = "#eb0000cc"
backgroundColor = "#52431946"
secondaryBackgroundColor = "#eca815ff"
textColor = "#1d0d3a8e"
font = "sans serif"
baseRadius="1rem"
buttonRadius="3rem"
borderColor="#0000008e"
# showWidgetBorder = 
# showSidebarBorder =


[server]
runOnSave= true
enableStaticServing = true